# Tutoriel package

Pour l'installation regarder README.

Pour bien comprendre ce petit tutoriel, un connaissance des algorithme du ducument Exact Matching of Random Graphs with Constant Correlation est nécessaire.
## Importation du paquet

In [1]:
import sigmaV1
import numpy as np

une seul fonction existe dans ce paquet qui est sigma()
## Erdös-Rényi Normal
On definie 2 graph de même nombre de noeud sous forme de matrice d'ajacente (type Array).

In [2]:
A=np.zeros((10,10))
#ici definition d'arete à la main. Pensez à utiliser un autre package pour générer automatiquement les graphs 
A[0,7]=1;A[7,0]=1;A[1,7]=1;A[7,1]=1;A[1,8]=1;A[8,1]=1;A[2,3]=1;A[3,2]=1;A[2,4]=1;A[4,2]=1;A[2,9]=1;A[9,2]=1;A[3,6]=1
A[6,3]=1;A[3,7]=1;A[7,3]=1;A[5,6]=1;A[6,5]=1;A[5,7]=1;A[7,5]=1;A[5,8]=1;A[8,5]=1;A[6,7]=1;A[7,6]=1;A[8,9]=1;A[9,8]=1
print(A)

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 1. 1. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 0.]
 [0. 0. 0. 1. 0. 1. 0. 1. 0. 0.]
 [1. 1. 0. 1. 0. 1. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0.]]


Une fois les deux matrices d'ajacences définient appeler la fonction sigma

Dans cette exemple j'utiliserais deux fois la même matrice A.

In [3]:
py=sigmaV1.sigma(A,A,2,0.3)

Les deux correspond au deux matrice d'ajacences des deux graph (dans l'exemple,c'est matrice seront les mêmes.)

    -le 2 correspond à la profondeur des arbre générer par cette méthode

    -0.3 correspond au p du graph Erdos-Renyi.

    -Le retour se fais sous forme de liste où le noeud de G2 associer au noeud X de G1 est à la place X dans la liste ( py[X] ).

    -Tous les arguments de sigma peuvent être nommés:

    -G1 pour le premier graph, G2 pour le deuxiéme, prof pour la profondeur et p pour p

In [4]:
py2=sigmaV1.sigma(prof=2,p=0.3,G1=A,G2=A)

Affichage des deux résultat. Attention ils peuvent être différent car les différent chemin sont générer aléatoirement. Deplus si deux noeud de G2 on même valeur de correlation alors on choisie aléatoirement entre les deux.

In [5]:
for i in range(len(py)):
    print(i,"=",py[i])
print()
for i in range(len(py2)):
    print(i,"=",py2[i])
print()

0 = 0
1 = 5
2 = 7
3 = 1
4 = 3
5 = 4
6 = 6
7 = 2
8 = 8
9 = 9

0 = 0
1 = 1
2 = 2
3 = 3
4 = 4
5 = 5
6 = 6
7 = 7
8 = 8
9 = 9



## Wigner Normal
Le passage de graph pour le modèle de Wigner se fait de la même façon que le modèle d'Erdos-Renyi (matrice d'ajacence)

In [6]:
B=np.zeros((10,10))

ici definition d'arete à la main. Pensez à utiliser un autre package pour générer automatiquement les graphs 



In [7]:
for i in range(B.shape[1]):
    for j in range(B.shape[1]):
        if (i==j):
            B[i,j]=np.random.normal(scale=2/10)
        else:
            B[i,j]=np.random.normal(scale=1/10)
            B[j,i]=B[i,j]
print(B)

[[-0.46621449  0.01096042  0.05230865 -0.10442761  0.0720668   0.07885965
  -0.04446942  0.01960544 -0.16005101  0.06110057]
 [ 0.01096042  0.30610524 -0.01126805 -0.11493126  0.11164774  0.03423545
  -0.06791617 -0.08790931  0.10051113  0.03148928]
 [ 0.05230865 -0.01126805  0.39996598 -0.11110143  0.01443391  0.26434099
   0.12302248  0.02496712 -0.03355023 -0.03685705]
 [-0.10442761 -0.11493126 -0.11110143 -0.28957532 -0.06986251 -0.02450013
  -0.11821199 -0.01030704 -0.06602162  0.07163936]
 [ 0.0720668   0.11164774  0.01443391 -0.06986251  0.19215546 -0.05996093
   0.10765951 -0.07008282 -0.02956327 -0.09552586]
 [ 0.07885965  0.03423545  0.26434099 -0.02450013 -0.05996093 -0.41684485
   0.10812324 -0.13144218  0.10419144  0.07853017]
 [-0.04446942 -0.06791617  0.12302248 -0.11821199  0.10765951  0.10812324
   0.24568417  0.01395778  0.03931925 -0.09214729]
 [ 0.01960544 -0.08790931  0.02496712 -0.01030704 -0.07008282 -0.13144218
   0.01395778 -0.16619429 -0.00679332  0.03536861]


Pour pouvoir utiliser la matrice d'ajacence il faux d'abord spacifier la matrice

In [8]:
C=np.zeros((10,10))
for i in range(B.shape[1]):
    for j in range(B.shape[1]):
        if(B[i,j]>0.04):
            C[i,j]=B[i,j]
print(C)

[[0.         0.         0.05230865 0.         0.0720668  0.07885965
  0.         0.         0.         0.06110057]
 [0.         0.30610524 0.         0.         0.11164774 0.
  0.         0.         0.10051113 0.        ]
 [0.05230865 0.         0.39996598 0.         0.         0.26434099
  0.12302248 0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.07163936]
 [0.0720668  0.11164774 0.         0.         0.19215546 0.
  0.10765951 0.         0.         0.        ]
 [0.07885965 0.         0.26434099 0.         0.         0.
  0.10812324 0.         0.10419144 0.07853017]
 [0.         0.         0.12302248 0.         0.10765951 0.10812324
  0.24568417 0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.10051113 0.         0.         0.         0.10419144
  0.         0.         0.         0.        ]
 [0.0

Une fois les deux matrices d'ajacences définient appeler la fonction sigma
Dans cette exemple j'utiliserais deux fois la même matrice C.

In [9]:
py3=sigmaV1.sigma(C,C,2)

File is empty
File is empty


Les deux correspond au deux matrice d'ajacences des deux graph (dans l'exemple,c'est matrice seront les mêmes.)
    -le 2 correspond à la profondeur des arbre générer par cette méthode
    -Pour que les calculs se fasse pour des graph de wigner n'enter pas de p ou donner lui -1
    -Les arguments peuvent ici aussi être nommés de la même façon que pour Normal Erdos

In [10]:
py4=sigmaV1.sigma(C,C,2,-1)

File is empty
File is empty


Affichage des deux résultat. Attention ils peuvent être différent car les différent chemin sont générer aléatoirement. Deplus si deux noeud de G2 on même valeur de correlation alors on choisie aléatoirement entre les deux.

In [11]:
for i in range(len(py3)):
    print(i,"=",py3[i])
print()
for i in range(len(py4)):
    print(i,"=",py4[i])
print()

0 = 5
1 = 1
2 = 2
3 = 3
4 = 6
5 = 0
6 = 8
7 = 7
8 = 4
9 = 9

0 = 0
1 = 1
2 = 2
3 = 3
4 = 8
5 = 5
6 = 4
7 = 7
8 = 6
9 = 9



## Choix Arbre de décision
Les Graph sont toujours passer de la même façon. Dans les exemples allons réutiliser le graph A

In [12]:
A=np.zeros((10,10))

ici definition d'arete à la main. Pensez à utiliser un autre package pour générer automatiquement les graphs 

In [13]:
A[0,7]=1;A[7,0]=1;A[1,7]=1;A[7,1]=1;A[1,8]=1;A[8,1]=1;A[2,3]=1;A[3,2]=1;A[2,4]=1;A[4,2]=1;A[2,9]=1;A[9,2]=1;A[3,6]=1
A[6,3]=1;A[3,7]=1;A[7,3]=1;A[5,6]=1;A[6,5]=1;A[5,7]=1;A[7,5]=1;A[5,8]=1;A[8,5]=1;A[6,7]=1;A[7,6]=1;A[8,9]=1;A[9,8]=1
print(A)

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 1. 1. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 0.]
 [0. 0. 0. 1. 0. 1. 0. 1. 0. 0.]
 [1. 1. 0. 1. 0. 1. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0.]]


Cette fois ci nous allons devoir definir trois fonctions permettant de d'écrire l'arbre ou les statistiques.

La première est celle de la classification des noeuds.
Cette fonction doit prendre en entre 1:une matrice d'ajacente, 2:un nombre correspondant au nom du noeud, 3: un floatant correspondant à p.
Cette fonction retournera un nombre entre 0(compris) et le nombre d'enfant possible dans l'arbre nbchild(non compris).
Vous pouvez renvoyer -1 avec cette fonction l'algorithme ne sera pas considèrer dans la classification de l'arbre. Cepandent ce noeud pourra être utilisé dans le calcul de la statistique

La seconde fonction correspond à la statistique f.
Cette fonction prendra aussi 3 arguments. 1:une matrice d'ajacente, 2:La liste des noeuds(entier) voisin de la feuille, 3: un floatant correspondant à p.
Cette fonction renvera le floattant f correspondant a cette liste

La Troisième fonction est très similaire la seconde fonction et correspond à la statistique v.
Cette fonction prendra aussi 3 arguments. 1:une matrice d'ajacente, 2:La liste des noeuds(entier) voisin de la feuille, 3: un floatant correspondant à p.
Cette fonction renvera le floattant v correspondant a cette liste

Nous allons faire 2 exemple pour ce cas. Le premier vous expliquera comment marche sigma avec le choix de la règle de décision. Le seconde exemple vous montrera comment mettre plus que 2 enfants.

### Exemple 1: reproduction du cas Erdös-Rényi normal
fonction de classification des noeuds (plus d'info sur le paragraphe ci dessus)

In [14]:
def normal_erdo(A,i,x):
    if (sum(A[i])<A.shape[1]*x) :
        return 0
    else :
        return 1

fonction de la statistique f (plus d'info sur le paragraphe ci dessus)

In [15]:
def f(graph_util,liste,p):
    retour=0
    for i in liste:
        retour+=sum(A[i])-A.shape[1]*p-1
    return retour

fonction de la statistique v (plus d'info sur le paragraphe ci dessus)

In [16]:
def v(graph_util,liste,p):
    retour=len(liste)*A.shape[1]*p*(1-p)
    return retour

Maintenant que les fonctions et les graphs ont été définis nous pouvont appeler sigma. Attention nous devrons passer à sigma le nombre d'enfant maximal de chaque noeud des arbres générés nbchild. Penser a passer p si nécessaire.

ici aussi nous pouvont appeler les arguments en les nommants
    -nbchild: nombre d'enfant maximal de chaque noeud des arbres générés
    -classi: fonction de classification des noeud de chaque graphe.
    -f: fonction de la statistique f
    -v: fonction de la statistique v

In [17]:
y=sigmaV1.sigma(A,A,2,0.3,2,normal_erdo,f,v)

Affichage du résultat. Les résultats sont toujours soumis au problème d'aléatoire preciser dans le cas Normal Erdös-Rényi  

In [18]:
for i in range(len(y)):
    print(i,"=",y[i])

0 = 3
1 = 4
2 = 2
3 = 9
4 = 1
5 = 5
6 = 0
7 = 7
8 = 8
9 = 6


# Exemple 2: cas avec trois enfant 
Le nombre d'enfant n'est pas limité et augmente de la même façon.
Fonction de classification des noeuds (plus d'info sur le paragraphe ci dessus)

In [19]:
def three_child(A,i,x):
    if (sum(A[i])<=A.shape[1]*x/3) :
        return 0
    elif (sum(A[i])>=A.shape[1]*x*5/3):
        return 1
    else:
        return 2

fonction de la statistique f (plus d'info sur le paragraphe ci dessus) inchanger

In [20]:
def f(graph_util,liste,p):
    retour=0
    for i in liste:
        retour+=sum(A[i])-A.shape[1]*p-1
    return retour

fonction de la statistique v (plus d'info sur le paragraphe ci dessus) inchanger

In [21]:
def v(graph_util,liste,p):
    retour=len(liste)*A.shape[1]*p*(1-p)
    return retour
y=sigmaV1.sigma(G1=A,G2=A,prof=2,p=0.3,nbchild=3,clas=three_child,f=f,v=v) 

affichage du résultat. Les résultats sont toujours soumis au problème d'aléatoire preciser dans le cas Normal Erdös-Rényi

In [22]:
for i in range(len(y)):
    print(i,"=",y[i])

0 = 0
1 = 1
2 = 2
3 = 5
4 = 4
5 = 3
6 = 7
7 = 6
8 = 8
9 = 9
